(library
  (name hipsleek_common)
  (public_name hipsleek.common)
  ;(libraries extlib fileutils batteries ocamlgraph camlp4 camlp4.lib xml-light)
  (libraries unix ocamlgraph camlp5 camlp-streams str num visitors.ppx)
    (inline_tests)
  (preprocess (per_module
    ((action (run camlp5o -loc _loc %{input-file})) parser)
    ((pps visitors.ppx ppx_expect) cpure_ast_typeinfer))))

(ocamllex
 (modules lexer rllexer z3mlexer oclexer))

(ocamlyacc
 (modules rlparser z3mparser ocparser))

(env
 (dev
  (flags
   (:standard -warn-error -A))))
