(library
  (public_name hipsleek)
  (libraries hipsleek.common hipsleek.cil ocamlgraph)
  (preprocess (per_module
    ((action (run cppo -I . -D TRACE %{input-file})) sleekmain typeclass monads cfsolver dda share_prover_w2 frame typechecker icontext rev_ast synUtils da stat_global rank ti3 piecewise scriptarguments checkeq nativefront syn_checkeq globalvars net lemutil iincr dp derive checks share_prover norm cpgraph term mona imminfer layout ti acc_fold cilparser icmd solver saout intsparser terminf slsat csvutil fixbag cleanUp pi sa3 lemsyn tlutils musterr saerror lemma vperm immutable auxnorm astsimp cpure_pred env cprog_sleek tpdispatcher fixUtil fixpoint slk2smt infinity pointers inliner log expure soutil syn cfutil iastUtil ti2 oast sacore sleekengine cputil coqinf fixcalc inferHP cfimmutils sap prooftracer label_aggr lp predicate sleekUtils mem lemproving classic termUtils context monadicinterp predcomp hgraph sautil typeinfer sleekcore template setmona cf_ext infer cvutil))))

(ocamllex
 (modules ilexer fixlexer))
; exclexer

(menhir
 (modules fixparser))

(ocamlyacc
 (modules iparser))

; run-oc new-mona test-oo


(env
 (dev
  (flags
   (:standard -warn-error -A))))
